export const SHOW_LOADER = 'SHOW_LOADER';

export const GET_CHARACTERS_LIST = 'GET_CHARACTERS_LIST';

export const CHANGE_FAVORITES = 'CHANGE_FAVORITES';

export const GET_PARAMS = 'GET_PARAMS';

export const SHOW_ERROR = 'SHOW_ERROR';
